/**
 * INSTAGRAM GRID — the photos shown in the "More than a gym, a collective"
 * section on the home page. Real posts from @thebarnfitnesscollective, saved
 * locally so the site stays fast and never depends on a live Instagram feed.
 *
 * This file is regenerated by scripts/update-instagram.mjs (see the
 * `barn-instagram` skill). You can also hand-edit it.
 */
export interface InstaPost {
  image: string; // filename in src/assets/images/
  alt: string;
}

export const instaPosts: InstaPost[] = [
  { image: "insta-01.jpg", alt: "We're the Barn Fitness Collective" },
  { image: "insta-02.jpg", alt: "Words of wisdom from Coach Chris" },
  { image: "insta-03.jpg", alt: "Everything is better with a friend — kickboxing" },
  { image: "insta-04.jpg", alt: "Throwback to our Pride workout" },
  { image: "insta-05.jpg", alt: "Pride Month raffle results" },
  { image: "insta-06.jpg", alt: "Behind the scenes at The Barn" },
];
