/**
 * INSTAGRAM GRID — the photos shown in the "More than a gym, a collective"
 * section on the home page. Real posts from @thebarnfitnesscollective, saved
 * locally so the site stays fast and never depends on a live Instagram feed.
 * Each tile links to its specific post.
 *
 * This file is regenerated by scripts/update-instagram.mjs (see the
 * `barn-instagram` skill). You can also hand-edit it.
 */
export interface InstaPost {
  image: string; // filename in src/assets/images/
  alt: string;
  link: string; // permalink to the specific post
}

export const instaPosts: InstaPost[] = [
  { image: "insta-01.jpg", alt: "We're the Barn Fitness Collective", link: "https://www.instagram.com/thebarnfitnesscollective/reel/DZ5vxOKy-JF/" },
  { image: "insta-02.jpg", alt: "Words of wisdom from Coach Chris", link: "https://www.instagram.com/thebarnfitnesscollective/reel/DaoUUFvFG6_/" },
  { image: "insta-03.jpg", alt: "Everything is better with a friend — kickboxing", link: "https://www.instagram.com/thebarnfitnesscollective/p/DaTrE6PHIzW/" },
  { image: "insta-04.jpg", alt: "Throwback to our Pride workout", link: "https://www.instagram.com/thebarnfitnesscollective/reel/DaOhZD1ijXi/" },
  { image: "insta-05.jpg", alt: "Pride Month raffle results", link: "https://www.instagram.com/thebarnfitnesscollective/reel/DaBnkr9PZ7i/" },
  { image: "insta-06.jpg", alt: "Behind the scenes at The Barn", link: "https://www.instagram.com/thebarnfitnesscollective/reel/DZx_r1CT-E-/" },
];
